-- https://onecompiler.com/mysql/3yk4j8mj2

-- create
CREATE TABLE DEPARTMENT (
  depId INTEGER PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  location VARCHAR(45) NOT NULL
);

CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name VARCHAR(45) NOT NULL,
  salary VARCHAR(45) NOT NULL,
  depId INTEGER,
  FOREIGN KEY (depId) REFERENCES DEPARTMENT(depId)
);

-- insert
INSERT INTO DEPARTMENT VALUES (0001, 'Executive', 'Sydney');
INSERT INTO DEPARTMENT VALUES (0002, 'Production', 'Sydney');
INSERT INTO DEPARTMENT VALUES (0003, 'Resources', 'Cape Town');
INSERT INTO DEPARTMENT VALUES (0004, 'Technical', 'Texas');
INSERT INTO DEPARTMENT VALUES (0005, 'Management', 'Paris');

INSERT INTO EMPLOYEE VALUES (0001, 'Candice', '4685', 0001);
INSERT INTO EMPLOYEE VALUES (0002, 'Julia', '2559', 0002);
INSERT INTO EMPLOYEE VALUES (0003, 'Bob', '4405', 0004);
INSERT INTO EMPLOYEE VALUES (0004, 'Scarlet', '2350', 0001);
INSERT INTO EMPLOYEE VALUES (0005, 'Ileana', '1151', 0004);

-- fetch
SELECT D.name, COUNT(*)
FROM DEPARTMENT D
INNER JOIN EMPLOYEE E
ON D.depId = E.depId
GROUP BY D.name
ORDER BY 2 DESC, 1 ASC;
